CREATE DATABASE A_Project;

USE A_Project;

CREATE TABLE export_data (
    YEAR INT,
    MONTH INT,
    SUPPLIER VARCHAR(255),
    `ITEM CODE` VARCHAR(100),
    `ITEM DESCRIPTION` VARCHAR(255),
    `ITEM TYPE` VARCHAR(100),
    `RETAIL SALES` DOUBLE,
    `RETAIL TRANSFERS` DOUBLE,
    `WAREHOUSE SALES` DOUBLE
);